  udt-api:
    build:
      context: ./udt-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://admin:admin123@mongo:27017/?authSource=admin
      - API_KEY=change_me_please

      # âœ… datasets you allow the API to use
      - ALLOWED_DBS=udt_dc_dev,udt_dc_prod,udt_tagio_dev,udt_tagio_prod,tag_dc_dev,tag_dc_prod,tag_tagio_dev,tag_tagio_prod
    depends_on:
      - mongo
